// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydcbzrqqnontgweansck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkY2J6cnFxbm9udGd3ZWFuc2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDc3MDYsImV4cCI6MjA2NjI4MzcwNn0.D0VRkmYyi3kFTKXYawU6nv62rCBwLacLVe5lrj5IaYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});